"""domain_models

Revision ID: 1b9a876eab13
Revises: e4c7ad0c4321
Create Date: 2026-06-03 21:30:17.200670
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b9a876eab13'
down_revision: str | None = 'e4c7ad0c4321'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationchannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_notificationchannel_type'), 'notificationchannel', ['type'], unique=False)
    op.create_table('ocicredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenancy_ocid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_ocid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('private_key_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passphrase_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocicredential_name'), 'ocicredential', ['name'], unique=True)
    op.create_table('instanceconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('shape', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ocpus', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Integer(), nullable=False),
    sa.Column('boot_volume_gb', sa.Integer(), nullable=False),
    sa.Column('image_ocid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subnet_ocid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('availability_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ssh_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_interval_sec', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['ocicredential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instance_ocid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['instanceconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_attempted_at'), 'attempt', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_attempt_config_id'), 'attempt', ['config_id'], unique=False)
    op.create_table('configchannellink',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notificationchannel.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['instanceconfig.id'], ),
    sa.PrimaryKeyConstraint('config_id', 'channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configchannellink')
    op.drop_index(op.f('ix_attempt_config_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_attempted_at'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_table('instanceconfig')
    op.drop_index(op.f('ix_ocicredential_name'), table_name='ocicredential')
    op.drop_table('ocicredential')
    op.drop_index(op.f('ix_notificationchannel_type'), table_name='notificationchannel')
    op.drop_table('notificationchannel')
    # ### end Alembic commands ###
