"""log_entry

Revision ID: e4c7ad0c4321
Revises: 7c268f67372f
Create Date: 2026-06-03 21:05:13.517097
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4c7ad0c4321'
down_revision: str | None = '7c268f67372f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exc_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logentry_config_id'), 'logentry', ['config_id'], unique=False)
    op.create_index(op.f('ix_logentry_level'), 'logentry', ['level'], unique=False)
    op.create_index(op.f('ix_logentry_logger'), 'logentry', ['logger'], unique=False)
    op.create_index(op.f('ix_logentry_timestamp'), 'logentry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logentry_timestamp'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_logger'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_level'), table_name='logentry')
    op.drop_index(op.f('ix_logentry_config_id'), table_name='logentry')
    op.drop_table('logentry')
    # ### end Alembic commands ###
